language: rust
rust:
  - nightly
cache: cargo
script:
  - cargo build --verbose --release --target=i686-unknown-linux-gnu
  - cargo build --verbose --release --target=x86_64-apple-darwin
  - cargo build --verbose --release --target=x86_64-unknown-freebsd
  - cargo build --verbose --release --target=i686-unknown-linux-gnu
  - cargo build --verbose --release --target=armv7-unknown-linux-gnueabihf
