language: rust
rust:
  - nightly
cache: cargo

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install dbus libdbus-1-dev libdbus-glib-1-dev libdbusmenu-gtk3-dev libcogl-pango-dev libpango1.0-dev libatk1.0-dev libatkmm-1.6-dev gnustep-devel gobjc

script:
  # - rustup target add i686-unknown-linux-gnu
  - rustup target add x86_64-apple-darwin
  # - rustup target add x86_64-unknown-freebsd
  # - rustup target add i686-unknown-linux-gnu
  # - rustup target add armv7-unknown-linux-gnueabihf
  - cargo build --release --target=x86_64-unknown-linux-gnu
  # - cargo build --verbose --release --target=i686-unknown-linux-gnu
  - cargo build --release --target=x86_64-apple-darwin
  # - cargo build --verbose --release --target=x86_64-unknown-freebsd
  # - cargo build --verbose --release --target=armv7-unknown-linux-gnueabihf

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: gh-pages
