language: rust
rust:
  - nightly
cache: cargo

before_install:
  - sudo wget http://win32builder.gnome.org/$LATEST_WIN64_GTK.zip
  - sudo mkdir /opt/gtkwin
  - sudo unzip $LATEST_WIN64_GTK.zip -d /opt/gtkwin
  - sudo chmod -R 777 /opt/gtkwin
  - cd /opt/gtkwin
  - find -name '*.pc' | while read pc; do sed -e "s@^prefix=.*@prefix=$PWD@" -i "$pc"; done
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install dbus libdbus-1-dev libdbus-glib-1-dev libdbusmenu-gtk3-dev libcogl-pango-dev libpango1.0-dev libatk1.0-dev libatkmm-1.6-dev mingw-w64 mingw-w64-x86-64-dev libgtk-3-dev
  - cd /home/travis/build/seanr707/gitter_gtk
  - pkg-config

script:
  - rustup target add x86_64-pc-windows-gnu
  - cargo build --release --target=x86_64-pc-windows-gnu

after_install:
  - mkdir /home/travis/build/seanr707/gitter_gtk/win64build
  - cp target/x86_64-pc-windows-gnu/release/*.exe /home/travis/build/seanr707/gitter_gtk/win64build
  - cp $GTK_INSTALL_PATH/bin/*.dll /home/travis/build/seanr707/gitter_gtk/win64build
  - mkdir -p /home/travis/build/seanr707/gitter_gtk/win64build/share/glib-2.0/schemas
  - mkdir /home/travis/build/seanr707/gitter_gtk/win64build/share/icons
  - cp $GTK_INSTALL_PATH/share/glib-2.0/schemas/* /home/travis/build/seanr707/gitter_gtk/win64build/share/glib-2.0/schemas
  - cp -r $GTK_INSTALL_PATH/share/icons/* /home/travis/build/seanr707/gitter_gtk/win64build/share/icons
  - zip -r gtk_gitter_win64.zip /home/travis/build/seanr707/gitter_gtk/win64build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: gh-pages
