environment:
  matrix:
    # - RUST: nightly
    # BITS: 32
    - RUST: nightly
      BITS: 64

cache:
  # - C:\msys64\mingw64
  - C:\Users\appveyor\.cargo
  - C:\projects\gitter-gtk\target

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host "%ARCH%-pc-windows-gnu" --default-toolchain %RUST% -y
  - SET PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;C:\Users\appveyor\.cargo\bin;%PATH%
  - pacman --noconfirm --needed -S mingw-w64-%ARCH%-gtk3 curl autoconf git libcurl-devel libcurl man vim binutils gcc make automake libtool pkg-config

build_script:
  - echo paths = ["."] > .cargo\config
  # - git clone -q --depth 50 -b build/windows https://github.com/seanr707/gitter_gtk
  - cd C:\projects\gitter-gtk
  - cargo build --release

after_build:
  - appveyor PushArtifact target/release/gitter_gtk
  - appveyor PushArtifact C:\projects\gitter-gkt\target\release\gitter_gtk

test: false

artifacts:
  - path: target/release/gitter_gtk
    name: gitter_gtk-win%BITS%
  - path: C:\projects\gitter-gkt\target\release\gitter_gtk
    name: gitter_gtk-win%BITS%

deploy:
  release: gitter_gtk-win64-dev-build$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: "%GITHUB_TOKEN%" # your encrypted token from GitHub
  artifact: gitter_gtk         # upload artifact
  draft: true
  prerelease: true
  on:
    branch: build/win64-dev
    appveyor_repo_tag: true
