environment:
  matrix:
    # - RUST: nightly
    # BITS: 32
    - RUST: nightly
      BITS: 64

cache:
  # - C:\msys64\mingw64
  - C:\Users\appveyor\.cargo
  - C:\projects\gitter-gtk\target

install:
  - SET APPVEYOR_SAVE_CACHE_ON_ERROR=true
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host "%ARCH%-pc-windows-gnu" --default-toolchain %RUST% -y
  - SET PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;C:\Users\appveyor\.cargo\bin;%PATH%
  - pacman --noconfirm --needed -S mingw-w64-%ARCH%-gtk3 curl autoconf git libcurl-devel libcurl man vim binutils gcc make automake libtool pkg-config

build_script:
  - echo paths = ["."] > .cargo\config
  # - git clone -q --depth 50 -b build/windows https://github.com/seanr707/gitter_gtk
  - cd C:\projects\gitter-gtk
  - cargo build --release

after_build:
  - appveyor PushArtifact ./target/release/gitter_gtk.exe
  # Prepping for release
  - mkdir gitter-gtk-win%BITS%
  - cp target/release/*.exe gitter-gtk-win%BITS%
  # Moving mingw DLLs into release folder
  - cp /mingw%BITS%/bin/*.dll gitter-gtk-win%BITS%
  # Creating release files to package GTK3 in release
  - mkdir gitter-gtk-win%BITS%\share
  - mkdir gitter-gtk-win%BITS%\share\glib-2.0
  - mkdir gitter-gtk-win%BITS%\share\glib-2.0\schemas
  - mkdir gitter-gtk-win%BITS%\share\icons
  - cp /mingw%BITS%/share/glib-2.0/schemas/* gitter-gtk-win%BITS%/share/glib-2.0/schemas
  - cp -r /mingw%BITS%/share/icons/* gitter-gtk-win%BITS%/share/icons
  # Set up folders for themes
  - mkdir gitter-gtk-win%BITS%\share\themes
  - mkdir gitter-gtk-win%BITS%\share\gtk-3.0
  # Copy for alt theme
  - cp -R ./gitter-gtk-win%BITS% ./gitter-gtk-win%BITS%-alt-theme
  # Get Windows GTK theme
  - git clone https://github.com/B00merang-Project/Windows-10.git ./gitter-gtk-win%BITS%/share/themes/Windows10
  # Set up settings to point to theme
  - touch gitter-gtk-win%BITS%/share/gtk-3.0/settings.ini
  - echo "[Settings]"\n\
    "gtk-theme-name = Windows10"\n\
    "gtk-font-name = Calibri 10"\n\
    "gtk-xft-rgba = rgb" > gitter-gtk-win%BITS%-alt-theme/share/gtk-3.0/settings.ini
  # Get Arc OSX GTK theme
  - git clone https://github.com/LinxGem33/OSX-Arc-Darker.git  gitter-gtk-win%BITS%-alt-theme/share/themes/OSX-Arc-Darker
  # Set up settings to point to theme
  - touch gitter-gtk-win%BITS%-alt-theme/share/gtk-3.0/settings.ini
  - echo "[Settings]"\n\
    "gtk-theme-name = OSX-Arc-Darker"\n\
    "gtk-font-name = Calibri 10"\n\
    "gtk-xft-rgba = rgb" > gitter-gtk-win%BITS%-alt-theme/share/gtk-3.0/settings.ini
  # Zipping up files for release
  - 7z a gitter-gtk-win%BITS%.zip gitter-gtk-win%BITS%
  - appveyor PushArtifact gitter-gtk-win%BITS%.zip
  - 7z a gitter-gtk-win%BITS%-alt-theme.zip gitter-gtk-win%BITS%-alt-theme
  - appveyor PushArtifact gitter-gtk-win%BITS%-alt-theme.zip

test: false

artifacts:
  - path: target\release\gitter_gtk.exe
    name: gitter_gtk

deploy:
  release: gitter_gtk-win64-dev-build$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: %GITHUB_TOKEN% # your encrypted token from GitHub
  artifact: gitter_gtk         # upload artifact
  draft: true
  appveyor_repo_tag: true
  prerelease: true
  on:
    branch: build/win64-dev
