environment:
  matrix:
    # - RUST: nightly
    # BITS: 32
    - RUST: nightly
      BITS: 64

cache:
  - C:\msys64
  - C:\Users\appveyor\.cargo

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host "%ARCH%-pc-windows-gnu" --default-toolchain %RUST% -y
  - SET PATH=C:\Users\appveyor\.cargo\bin;%PATH%;C:\msys64\usr\bin # C:\msys64\mingw%BITS%\bin
  - rustc -Vv
  - cargo -Vv
  - pacman --noconfirm --needed -S mingw-w64-%ARCH%-gtk3 curl autoconf git libcurl-devel libcurl man vim binutils gcc make automake libtool pkg-config

build_script:
  - echo paths = ["."] > .cargo\config
  # - git clone -q --depth 50 -b build/windows https://github.com/seanr707/gitter_gtk
  - cd C:\projects\gitter-gtk
  - cargo build --release

test: false
